import type { Destination, FeedItem, Friend, Tier } from './types'

export const DESTINATIONS: Destination[] = [
  {
    name: 'Kyoto', country: 'Japon', lat: 35.01, lng: 135.77, tier: 'S',
    image: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?auto=format&fit=crop&w=900&q=85',
    score: 4.9, notes: 24,
    summary: 'Entre traditions ancestrales et modernite discrete, Kyoto enchante a chaque saison.',
    coupDeCoeur: true,
    food: 5, night: 4, culture: 5, nature: 5, value: 4, intent: 'tourisme',
  },
  {
    name: 'Bali', country: 'Indonesie', lat: -8.34, lng: 115.09, tier: 'S',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=900&q=85',
    score: 4.8, notes: 31,
    summary: 'Rizieres, temples et plages douces pour une parenthese lumineuse.',
    food: 5, night: 4, culture: 5, nature: 5, value: 5, intent: 'nature',
  },
  {
    name: 'Lisbonne', country: 'Portugal', lat: 38.71, lng: -9.14, tier: 'A',
    image: 'https://images.unsplash.com/photo-1548707309-dcebeab9ea9b?auto=format&fit=crop&w=900&q=85',
    score: 4.4, notes: 18,
    summary: 'Collines dorees, azulejos et soirees a taille humaine.',
    food: 4, night: 4, culture: 4, nature: 3, value: 5, intent: 'city-trip',
  },
  {
    name: 'Le Cap', country: 'Afrique du Sud', lat: -33.92, lng: 18.42, tier: 'A',
    image: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=900&q=85',
    score: 4.3, notes: 15,
    summary: 'Ocean, montagnes et quartiers creatifs dans un meme souffle.',
    food: 4, night: 4, culture: 4, nature: 5, value: 4, intent: 'nature',
  },
  {
    name: 'Vancouver', country: 'Canada', lat: 49.28, lng: -123.12, tier: 'A',
    image: 'https://images.unsplash.com/photo-1560814304-4f05b62af116?auto=format&fit=crop&w=900&q=85',
    score: 4.2, notes: 12,
    summary: 'Ville fraiche, nature immediate et ambiance pacifique.',
    food: 4, night: 3, culture: 4, nature: 5, value: 3, intent: 'nature',
  },
  {
    name: 'Barcelone', country: 'Espagne', lat: 41.38, lng: 2.15, tier: 'A',
    image: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&w=900&q=85',
    score: 4.4, notes: 20,
    summary: 'Architecture solaire, tapas, plage et nuits animees.',
    tripYear: 2024, tripDays: 5, companions: 'amis', personalBudget: 450, standout: 'Ambiance',
    food: 5, night: 5, culture: 4, nature: 3, value: 4, intent: 'sorties',
  },
  {
    name: 'Italie', country: 'Italie', lat: 42.7, lng: 12.4, tier: 'A',
    kind: 'zone',
    image: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=900&q=85',
    score: 4.1, notes: 4,
    tripYear: 2025, tripDays: 12, companions: 'amis', personalBudget: 980, standout: 'Paysages',
    extent: [6.4, 36.4, 18.7, 46.7],
    stops: [
      { name: 'Turin', lat: 45.07, lng: 7.69, type: 'stage' },
      { name: 'Venise', lat: 45.44, lng: 12.33, type: 'stage' },
      { name: 'Trogir', lat: 43.52, lng: 16.25, type: 'stage' },
      { name: 'Taormine', lat: 37.85, lng: 15.29, type: 'stage' },
    ],
    food: 5, night: 3, culture: 5, nature: 4, value: 3, intent: 'tourisme',
  },
  {
    name: 'Bangkok', country: 'Thailande', lat: 13.75, lng: 100.5, tier: 'B',
    image: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=900&q=85',
    score: 3.7, notes: 16,
    summary: 'Energie dense, street food mythique et temples dores.',
    food: 5, night: 5, culture: 4, nature: 2, value: 5, intent: 'gastro',
  },
  {
    name: 'Mexico', country: 'Mexique', lat: 19.43, lng: -99.13, tier: 'B',
    image: 'https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?auto=format&fit=crop&w=900&q=85',
    score: 3.6, notes: 11,
    summary: 'Musees, marches, couleurs franches et grande cuisine.',
    food: 5, night: 4, culture: 5, nature: 2, value: 4, intent: 'tourisme',
  },
  {
    name: 'Santorin', country: 'Grece', lat: 36.39, lng: 25.46, tier: 'C',
    image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=900&q=85',
    score: 2.5, notes: 9,
    summary: 'Falaises blanches, lumiere bleue et vues tres demandees.',
    food: 3, night: 3, culture: 3, nature: 4, value: 2, intent: 'tourisme',
  },
  {
    name: 'Dubai', country: 'Emirats arabes unis', lat: 25.2, lng: 55.27, tier: 'C',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=900&q=85',
    score: 2.6, notes: 8,
    summary: 'Skyline spectaculaire, hotels precis et desert a portee de route.',
    food: 4, night: 4, culture: 2, nature: 2, value: 1, intent: 'travail',
  },
  {
    name: 'Rio de Janeiro', country: 'Bresil', lat: -22.91, lng: -43.17, tier: 'C',
    image: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=900&q=85',
    score: 2.8, notes: 13,
    summary: 'Relief dramatique, plage vivante et rythme immediat.',
    food: 3, night: 5, culture: 4, nature: 5, value: 3, intent: 'sorties',
  },
  {
    name: 'New York', country: 'Etats-Unis', lat: 40.71, lng: -74.0, tier: 'D',
    image: 'https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?auto=format&fit=crop&w=900&q=85',
    score: 3.1, notes: 19,
    summary: 'Intense, brillante, chere, mais impossible a ignorer.',
    food: 5, night: 5, culture: 5, nature: 1, value: 1, intent: 'city-trip',
  },
  {
    name: 'Auckland', country: 'Nouvelle-Zelande', lat: -36.85, lng: 174.76, tier: 'D',
    image: 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?auto=format&fit=crop&w=900&q=85',
    score: 2.0, notes: 7,
    summary: 'Base paisible avant les grands paysages neo-zelandais.',
    food: 3, night: 2, culture: 3, nature: 5, value: 2, intent: 'nature',
  },
]

export const FRIENDS: Friend[] = [
  { initials: 'AS', name: 'Alex S.', color: '#0f6e56', bg: '#e1f5ee', count: 24 },
  { initials: 'LM', name: 'Lea M.', color: '#534ab7', bg: '#eeedfe', count: 17 },
  { initials: 'JB', name: 'Jules B.', color: '#993c1d', bg: '#faece7', count: 31 },
]

export const FEED: FeedItem[] = [
  { friend: 'AS', dest: 'Kyoto', flag: 'JP', tier: 'S', time: 'Il y a 2h', lat: 35.01, lng: 135.77 },
  { friend: 'LM', dest: 'Seville', flag: 'ES', tier: 'A', time: 'Hier', lat: 37.39, lng: -5.99 },
  { friend: 'JB', dest: 'Buenos Aires', flag: 'AR', tier: 'B', time: 'Hier', lat: -34.61, lng: -58.38 },
]

export const FRIEND_DESTINATIONS: Record<string, Destination[]> = {
  AS: DESTINATIONS.slice(0, 7),
  LM: DESTINATIONS.slice(2, 9),
  JB: DESTINATIONS.slice(5),
}

export const TIER_COLORS: Record<Tier, { pin: string; label: string }> = {
  S: { pin: '#f25f73', label: '#d93f58' },
  A: { pin: '#fb8b45', label: '#e9782f' },
  B: { pin: '#ffc94a', label: '#d89a05' },
  C: { pin: '#61c77a', label: '#3eae5f' },
  D: { pin: '#657cff', label: '#5066e7' },
}

export const TIER_ORDER: Tier[] = ['S', 'A', 'B', 'C', 'D']

export const CITY_COORDS: Record<string, { lat: number; lng: number }> = Object.fromEntries(
  DESTINATIONS.map(destination => [destination.name, { lat: destination.lat, lng: destination.lng }]),
)

export type Continent = 'Europe' | 'Asie' | 'Ameriques' | 'Afrique' | 'Oceanie'

export const COUNTRY_TO_CONTINENT: Record<string, Continent> = {
  // Europe — ouest
  'Portugal': 'Europe',
  'Espagne': 'Europe',
  'France': 'Europe',
  'Italie': 'Europe',
  'Royaume-Uni': 'Europe',
  'Angleterre': 'Europe',
  'Écosse': 'Europe',
  'Ecosse': 'Europe',
  'Irlande': 'Europe',
  'Allemagne': 'Europe',
  'Pays-Bas': 'Europe',
  'Belgique': 'Europe',
  'Luxembourg': 'Europe',
  'Suisse': 'Europe',
  'Autriche': 'Europe',
  'Danemark': 'Europe',
  'Suède': 'Europe',
  'Suede': 'Europe',
  'Norvège': 'Europe',
  'Norvege': 'Europe',
  'Finlande': 'Europe',
  'Islande': 'Europe',
  // Europe — sud & est
  'Grèce': 'Europe',
  'Grece': 'Europe',
  'Croatie': 'Europe',
  'Slovénie': 'Europe',
  'Slovenie': 'Europe',
  'Bosnie-Herzégovine': 'Europe',
  'Monténégro': 'Europe',
  'Montenegro': 'Europe',
  'Serbie': 'Europe',
  'Albanie': 'Europe',
  'Bulgarie': 'Europe',
  'Roumanie': 'Europe',
  'Moldavie': 'Europe',
  'Ukraine': 'Europe',
  'Pologne': 'Europe',
  'République tchèque': 'Europe',
  'Republique tcheque': 'Europe',
  'Tchéquie': 'Europe',
  'Tcheque': 'Europe',
  'Slovaquie': 'Europe',
  'Hongrie': 'Europe',
  'Estonie': 'Europe',
  'Lettonie': 'Europe',
  'Lituanie': 'Europe',
  'Biélorussie': 'Europe',
  'Bielorussie': 'Europe',
  'Russie': 'Europe',
  'Malte': 'Europe',
  'Chypre': 'Europe',
  'Monaco': 'Europe',
  'Andorre': 'Europe',
  'Kosovo': 'Europe',
  'Macédoine du Nord': 'Europe',
  'Macedoine du Nord': 'Europe',
  // Asie — est & sud-est
  'Japon': 'Asie',
  'Chine': 'Asie',
  'Corée du Sud': 'Asie',
  'Coree du Sud': 'Asie',
  'Taïwan': 'Asie',
  'Taiwan': 'Asie',
  'Hong Kong': 'Asie',
  'Mongolie': 'Asie',
  'Indonésie': 'Asie',
  'Indonesie': 'Asie',
  'Thaïlande': 'Asie',
  'Thailande': 'Asie',
  'Vietnam': 'Asie',
  'Cambodge': 'Asie',
  'Laos': 'Asie',
  'Myanmar': 'Asie',
  'Birmanie': 'Asie',
  'Malaisie': 'Asie',
  'Singapour': 'Asie',
  'Philippines': 'Asie',
  // Asie — sud
  'Inde': 'Asie',
  'Pakistan': 'Asie',
  'Bangladesh': 'Asie',
  'Sri Lanka': 'Asie',
  'Népal': 'Asie',
  'Nepal': 'Asie',
  'Maldives': 'Asie',
  // Asie — proche-orient & centrale
  'Émirats arabes unis': 'Asie',
  'Emirats arabes unis': 'Asie',
  'Arabie saoudite': 'Asie',
  'Qatar': 'Asie',
  'Koweït': 'Asie',
  'Koweit': 'Asie',
  'Bahreïn': 'Asie',
  'Bahrein': 'Asie',
  'Oman': 'Asie',
  'Irak': 'Asie',
  'Iran': 'Asie',
  'Jordanie': 'Asie',
  'Liban': 'Asie',
  'Israël': 'Asie',
  'Israel': 'Asie',
  'Palestine': 'Asie',
  'Turquie': 'Asie',
  'Géorgie': 'Asie',
  'Georgie': 'Asie',
  'Arménie': 'Asie',
  'Armenie': 'Asie',
  'Azerbaïdjan': 'Asie',
  'Azerbaidjan': 'Asie',
  'Kazakhstan': 'Asie',
  'Ouzbékistan': 'Asie',
  'Ouzbekistan': 'Asie',
  'Kirghizistan': 'Asie',
  'Tadjikistan': 'Asie',
  'Afghanistan': 'Asie',
  // Amériques — nord & centrale
  'Canada': 'Ameriques',
  'États-Unis': 'Ameriques',
  'Etats-Unis': 'Ameriques',
  'Mexique': 'Ameriques',
  'Cuba': 'Ameriques',
  'Jamaïque': 'Ameriques',
  'Jamaique': 'Ameriques',
  'Haïti': 'Ameriques',
  'Haiti': 'Ameriques',
  'République dominicaine': 'Ameriques',
  'Republique dominicaine': 'Ameriques',
  'Costa Rica': 'Ameriques',
  'Panama': 'Ameriques',
  'Guatemala': 'Ameriques',
  'Honduras': 'Ameriques',
  'Nicaragua': 'Ameriques',
  'Belize': 'Ameriques',
  // Amériques — sud
  'Colombie': 'Ameriques',
  'Venezuela': 'Ameriques',
  'Équateur': 'Ameriques',
  'Equateur': 'Ameriques',
  'Pérou': 'Ameriques',
  'Perou': 'Ameriques',
  'Brésil': 'Ameriques',
  'Bresil': 'Ameriques',
  'Bolivie': 'Ameriques',
  'Paraguay': 'Ameriques',
  'Uruguay': 'Ameriques',
  'Argentine': 'Ameriques',
  'Chili': 'Ameriques',
  // Afrique — nord
  'Maroc': 'Afrique',
  'Algérie': 'Afrique',
  'Algerie': 'Afrique',
  'Tunisie': 'Afrique',
  'Libye': 'Afrique',
  'Égypte': 'Afrique',
  'Egypte': 'Afrique',
  // Afrique — ouest
  'Sénégal': 'Afrique',
  'Senegal': 'Afrique',
  "Côte d'Ivoire": 'Afrique',
  "Cote d'Ivoire": 'Afrique',
  'Ghana': 'Afrique',
  'Nigeria': 'Afrique',
  'Cameroun': 'Afrique',
  'Mali': 'Afrique',
  'Guinée': 'Afrique',
  'Guinee': 'Afrique',
  // Afrique — est & sud
  'Kenya': 'Afrique',
  'Tanzanie': 'Afrique',
  'Ouganda': 'Afrique',
  'Rwanda': 'Afrique',
  'Éthiopie': 'Afrique',
  'Ethiopie': 'Afrique',
  'Mozambique': 'Afrique',
  'Zambie': 'Afrique',
  'Zimbabwe': 'Afrique',
  'Madagascar': 'Afrique',
  'Afrique du Sud': 'Afrique',
  'Namibie': 'Afrique',
  'Botswana': 'Afrique',
  'Île Maurice': 'Afrique',
  'Ile Maurice': 'Afrique',
  'Maurice': 'Afrique',
  'Mauritius': 'Afrique',
  'Réunion': 'Afrique',
  'Reunion': 'Afrique',
  'La Réunion': 'Afrique',
  'La Reunion': 'Afrique',
  'Seychelles': 'Afrique',
  'Cap-Vert': 'Afrique',
  // Océanie
  'Australie': 'Oceanie',
  'Nouvelle-Zélande': 'Oceanie',
  'Nouvelle-Zelande': 'Oceanie',
  'Fidji': 'Oceanie',
  'Vanuatu': 'Oceanie',
  'Polynésie française': 'Oceanie',
  'Polynesie francaise': 'Oceanie',
  'Nouvelle-Calédonie': 'Oceanie',
  'Nouvelle-Caledonie': 'Oceanie',
}

export const CONTINENTS: Continent[] = ['Europe', 'Asie', 'Ameriques', 'Afrique', 'Oceanie']
